//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumInterface.TimelineReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TimelineReference.ITimelineService")]
    public interface ITimelineService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getAllMovies", ReplyAction="http://tempuri.org/ITimelineService/getAllMoviesResponse")]
        System.Collections.Generic.List<int> getAllMovies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getAllMovies", ReplyAction="http://tempuri.org/ITimelineService/getAllMoviesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<int>> getAllMoviesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getSortedMovies", ReplyAction="http://tempuri.org/ITimelineService/getSortedMoviesResponse")]
        System.Collections.Generic.List<int> getSortedMovies(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getSortedMovies", ReplyAction="http://tempuri.org/ITimelineService/getSortedMoviesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<int>> getSortedMoviesAsync(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getMovieImage", ReplyAction="http://tempuri.org/ITimelineService/getMovieImageResponse")]
        string getMovieImage(int movieID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getMovieImage", ReplyAction="http://tempuri.org/ITimelineService/getMovieImageResponse")]
        System.Threading.Tasks.Task<string> getMovieImageAsync(int movieID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getMovieTitle", ReplyAction="http://tempuri.org/ITimelineService/getMovieTitleResponse")]
        string getMovieTitle(int movieID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getMovieTitle", ReplyAction="http://tempuri.org/ITimelineService/getMovieTitleResponse")]
        System.Threading.Tasks.Task<string> getMovieTitleAsync(int movieID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getMovieYear", ReplyAction="http://tempuri.org/ITimelineService/getMovieYearResponse")]
        int getMovieYear(int movieID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getMovieYear", ReplyAction="http://tempuri.org/ITimelineService/getMovieYearResponse")]
        System.Threading.Tasks.Task<int> getMovieYearAsync(int movieID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getMoviePreview", ReplyAction="http://tempuri.org/ITimelineService/getMoviePreviewResponse")]
        string getMoviePreview(int movieID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getMoviePreview", ReplyAction="http://tempuri.org/ITimelineService/getMoviePreviewResponse")]
        System.Threading.Tasks.Task<string> getMoviePreviewAsync(int movieID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getMoviePlot", ReplyAction="http://tempuri.org/ITimelineService/getMoviePlotResponse")]
        string getMoviePlot(int movieID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getMoviePlot", ReplyAction="http://tempuri.org/ITimelineService/getMoviePlotResponse")]
        System.Threading.Tasks.Task<string> getMoviePlotAsync(int movieID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getMovieCategories", ReplyAction="http://tempuri.org/ITimelineService/getMovieCategoriesResponse")]
        System.Collections.Generic.List<string> getMovieCategories(int movieID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getMovieCategories", ReplyAction="http://tempuri.org/ITimelineService/getMovieCategoriesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> getMovieCategoriesAsync(int movieID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getRating", ReplyAction="http://tempuri.org/ITimelineService/getRatingResponse")]
        int getRating(int movieID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getRating", ReplyAction="http://tempuri.org/ITimelineService/getRatingResponse")]
        System.Threading.Tasks.Task<int> getRatingAsync(int movieID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getComment", ReplyAction="http://tempuri.org/ITimelineService/getCommentResponse")]
        int getComment(int movieID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getComment", ReplyAction="http://tempuri.org/ITimelineService/getCommentResponse")]
        System.Threading.Tasks.Task<int> getCommentAsync(int movieID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getFeaturedMovies", ReplyAction="http://tempuri.org/ITimelineService/getFeaturedMoviesResponse")]
        System.Collections.Generic.List<int> getFeaturedMovies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getFeaturedMovies", ReplyAction="http://tempuri.org/ITimelineService/getFeaturedMoviesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<int>> getFeaturedMoviesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getTrendingMovies", ReplyAction="http://tempuri.org/ITimelineService/getTrendingMoviesResponse")]
        System.Collections.Generic.List<int> getTrendingMovies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getTrendingMovies", ReplyAction="http://tempuri.org/ITimelineService/getTrendingMoviesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<int>> getTrendingMoviesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getMovieComments", ReplyAction="http://tempuri.org/ITimelineService/getMovieCommentsResponse")]
        System.Collections.Generic.List<int> getMovieComments(int movieID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getMovieComments", ReplyAction="http://tempuri.org/ITimelineService/getMovieCommentsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<int>> getMovieCommentsAsync(int movieID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getCommenter", ReplyAction="http://tempuri.org/ITimelineService/getCommenterResponse")]
        int getCommenter(int commentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getCommenter", ReplyAction="http://tempuri.org/ITimelineService/getCommenterResponse")]
        System.Threading.Tasks.Task<int> getCommenterAsync(int commentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getCommentRate", ReplyAction="http://tempuri.org/ITimelineService/getCommentRateResponse")]
        int getCommentRate(int commentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getCommentRate", ReplyAction="http://tempuri.org/ITimelineService/getCommentRateResponse")]
        System.Threading.Tasks.Task<int> getCommentRateAsync(int commentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getCommentDesc", ReplyAction="http://tempuri.org/ITimelineService/getCommentDescResponse")]
        string getCommentDesc(int commentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getCommentDesc", ReplyAction="http://tempuri.org/ITimelineService/getCommentDescResponse")]
        System.Threading.Tasks.Task<string> getCommentDescAsync(int commentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getCommentTime", ReplyAction="http://tempuri.org/ITimelineService/getCommentTimeResponse")]
        string getCommentTime(int commentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimelineService/getCommentTime", ReplyAction="http://tempuri.org/ITimelineService/getCommentTimeResponse")]
        System.Threading.Tasks.Task<string> getCommentTimeAsync(int commentID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITimelineServiceChannel : ForumInterface.TimelineReference.ITimelineService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimelineServiceClient : System.ServiceModel.ClientBase<ForumInterface.TimelineReference.ITimelineService>, ForumInterface.TimelineReference.ITimelineService {
        
        public TimelineServiceClient() {
        }
        
        public TimelineServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TimelineServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimelineServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimelineServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<int> getAllMovies() {
            return base.Channel.getAllMovies();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<int>> getAllMoviesAsync() {
            return base.Channel.getAllMoviesAsync();
        }
        
        public System.Collections.Generic.List<int> getSortedMovies(string category) {
            return base.Channel.getSortedMovies(category);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<int>> getSortedMoviesAsync(string category) {
            return base.Channel.getSortedMoviesAsync(category);
        }
        
        public string getMovieImage(int movieID) {
            return base.Channel.getMovieImage(movieID);
        }
        
        public System.Threading.Tasks.Task<string> getMovieImageAsync(int movieID) {
            return base.Channel.getMovieImageAsync(movieID);
        }
        
        public string getMovieTitle(int movieID) {
            return base.Channel.getMovieTitle(movieID);
        }
        
        public System.Threading.Tasks.Task<string> getMovieTitleAsync(int movieID) {
            return base.Channel.getMovieTitleAsync(movieID);
        }
        
        public int getMovieYear(int movieID) {
            return base.Channel.getMovieYear(movieID);
        }
        
        public System.Threading.Tasks.Task<int> getMovieYearAsync(int movieID) {
            return base.Channel.getMovieYearAsync(movieID);
        }
        
        public string getMoviePreview(int movieID) {
            return base.Channel.getMoviePreview(movieID);
        }
        
        public System.Threading.Tasks.Task<string> getMoviePreviewAsync(int movieID) {
            return base.Channel.getMoviePreviewAsync(movieID);
        }
        
        public string getMoviePlot(int movieID) {
            return base.Channel.getMoviePlot(movieID);
        }
        
        public System.Threading.Tasks.Task<string> getMoviePlotAsync(int movieID) {
            return base.Channel.getMoviePlotAsync(movieID);
        }
        
        public System.Collections.Generic.List<string> getMovieCategories(int movieID) {
            return base.Channel.getMovieCategories(movieID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> getMovieCategoriesAsync(int movieID) {
            return base.Channel.getMovieCategoriesAsync(movieID);
        }
        
        public int getRating(int movieID) {
            return base.Channel.getRating(movieID);
        }
        
        public System.Threading.Tasks.Task<int> getRatingAsync(int movieID) {
            return base.Channel.getRatingAsync(movieID);
        }
        
        public int getComment(int movieID) {
            return base.Channel.getComment(movieID);
        }
        
        public System.Threading.Tasks.Task<int> getCommentAsync(int movieID) {
            return base.Channel.getCommentAsync(movieID);
        }
        
        public System.Collections.Generic.List<int> getFeaturedMovies() {
            return base.Channel.getFeaturedMovies();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<int>> getFeaturedMoviesAsync() {
            return base.Channel.getFeaturedMoviesAsync();
        }
        
        public System.Collections.Generic.List<int> getTrendingMovies() {
            return base.Channel.getTrendingMovies();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<int>> getTrendingMoviesAsync() {
            return base.Channel.getTrendingMoviesAsync();
        }
        
        public System.Collections.Generic.List<int> getMovieComments(int movieID) {
            return base.Channel.getMovieComments(movieID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<int>> getMovieCommentsAsync(int movieID) {
            return base.Channel.getMovieCommentsAsync(movieID);
        }
        
        public int getCommenter(int commentID) {
            return base.Channel.getCommenter(commentID);
        }
        
        public System.Threading.Tasks.Task<int> getCommenterAsync(int commentID) {
            return base.Channel.getCommenterAsync(commentID);
        }
        
        public int getCommentRate(int commentID) {
            return base.Channel.getCommentRate(commentID);
        }
        
        public System.Threading.Tasks.Task<int> getCommentRateAsync(int commentID) {
            return base.Channel.getCommentRateAsync(commentID);
        }
        
        public string getCommentDesc(int commentID) {
            return base.Channel.getCommentDesc(commentID);
        }
        
        public System.Threading.Tasks.Task<string> getCommentDescAsync(int commentID) {
            return base.Channel.getCommentDescAsync(commentID);
        }
        
        public string getCommentTime(int commentID) {
            return base.Channel.getCommentTime(commentID);
        }
        
        public System.Threading.Tasks.Task<string> getCommentTimeAsync(int commentID) {
            return base.Channel.getCommentTimeAsync(commentID);
        }
    }
}
