//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForumServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public long acc_ID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string emailAdd { get; set; }
        public string profile_picture { get; set; }
        public string bio { get; set; }
    }
}
