//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForumServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class movie_category
    {
        public long ID { get; set; }
        public long Category_ID { get; set; }
        public long Movie_ID { get; set; }
    }
}
