//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForumServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class movie
    {
        public long ID { get; set; }
        public string plot { get; set; }
        public string title { get; set; }
        public long year { get; set; }
        public string poster { get; set; }
        public Nullable<long> rating { get; set; }
        public string preview { get; set; }
    }
}
